In [1]:
import pandas as pd

In [2]:
import imxUtilities as utils

In [3]:
data = utils.data.tickets_data()

In [4]:
data

,ticket_number,internal_id,company_name,jobsite,date,attribute_date,employees,num_of_employees,tare_weight,gross_weight,net_weight,hours_worked,material_type,rate
0,308466,1004,JBI Scrap Processors,JBI,2022-02-02,2022-02-02,unknown,1,0,0,25900,0,5_foot_heavy_torching,30
1,308467,1005,JBI Scrap Processors,JBI,2022-02-02,2022-02-02,unknown,1,0,0,28100,0,5_foot_heavy_torching,30
2,308468,1006,JBI Scrap Processors,JBI,2022-02-02,2022-02-02,unknown,1,0,0,40400,0,5_foot_heavy_torching,30
3,308470,1007,JBI Scrap Processors,JBI,2022-02-02,2022-02-02,unknown,1,0,0,26800,0,5_foot_heavy_torching,30
4,158598,1008,Cohen Recycling,Sardinia,2022-01-19,2022-01-19,unknown,1,64320,42880,21440,0,5_foot_heavy_torching,30
5,11111,1009,Cohen Recycling,Sardinia,2022-02-01,2022-02-01,unknown,1,0,0,100,0,2 Foot: 65.0,0
6,222222,1010,Cohen Recycling,Macon,2022-02-02,2022-02-02,unknown,1,0,0,200,0,3 Foot: 50.0,0
7,12345,1011,"Redline Metalsl, Inc.",Redline,2022-02-03,2022-02-03,unknown,1,0,0,100,0,Heavy Metal_5,30
8,123456,1012,"Redline Metalsl, Inc.",Redline,2022-02-03,2022-02-03,unknown,1,0,0,100,0,Heavy Metal_5,100
9,1234567,1013,"Redline Metalsl, Inc.",Redline,2022-02-03,2022-02-03,unknown,1,0,0,100,0,Heavy Metal_5,100
10,123455,1014,"Redline Metalsl, Inc.",Redline,2022-02-03,2022-02-03,unknown,1,0,0,100,0,1 Foot,60
11,54321,1015,Kimmel Scrap Iron & Metal,Detroit Yard,2022-02-05,2022-02-05,unknown,1,0,0,100,0,Clip,30
12,19050,1016,Cohen Recycling,Sardinia,2022-01-19,2022-01-19,unknown,1,61620,42540,19080,0,Cast,55
13,308469,1017,JBI Scrap Processors,JBI,2022-02-02,2022-02-02,unknown,1,0,0,25900,0,3 Foot,50
14,654321,1018,JBI Scrap Processors,JBI,2022-02-02,2022-02-01,gerardo sandoval,1,0,0,500,0,3 Foot,50
15,22345,1020,JBI Scrap Processors,JBI,2022-02-02,2022-02-02,"chato dog, apples are",2,0,0,500,0,Heavy Metal_5,35

In [5]:
def duplicate_ticket(ticket_number, company):
    ticket_data = utils.data.tickets_data()
    dup_ticket = int(ticket_number) in list(ticket_data['ticket_number'])
    if not dup_ticket:
        return dup_ticket
    else:
        ticket_df = ticket_data[ticket_data['ticket_number'] == int(ticket_number)]
        if company in list(ticket_df['company_name']):
            return True
        else:
            return False

In [6]:
duplicate_ticket(22345, "JBI Scrap Processors")

True

In [7]:
duplicate_ticket(22345, "Apples")

False

In [8]:
duplicate_ticket(1234, "Apples")

False

In [9]:
duplicate_ticket(22345, "Apples")

False

In [10]:
duplicate_ticket(22345, "JBI")

False